apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.metadata.name }}-ingress
spec:
  rules:
  - host: {{ .Values.metadata.name }}.{{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.metadata.name }}-nodeport
          servicePort: {{ .Values.ports.servicePort }}