apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}-nodeport
spec:
  type: NodePort
  selector:
    app: {{ .Values.metadata.name }}
  ports:
  - port: {{ .Values.ports.servicePort }}
    targetPort: {{ .Values.ports.containerPort }}