{
 "title": "tensorfood_prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rate of Prediction Requests (Default)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(seldon_api_executor_client_requests_seconds_count[5m])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(BENTOML_TensorfoodTensorflow_request_total{endpoint=\"/predict\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Latency Distribution (Custom)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(model_process_latency_seconds_bucket[10m])) by (le)",
     "legendFormat": "{{le}} s"
    }
   ]
  },
  {
   "title": "Rate of Failures (Custom)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_failures_count_total[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Confidence (Custom)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "branch_confidence", "legendFormat": "{{model_name}}" }
   ]
  }
 ]
}